version: 0.1
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run export
  # post_build: # Build 완료 후에 할 작업
  #   commands:
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
